name: Add Labels

permissions:
  pull-requests: write

on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  add_supporters:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.pull_request.title, 'Answer') }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i @actions/core @actions/github

      - name: Add labels
        uses: ./.github/github-action/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
